# ==============================================================================
# FILE: .github/dependabot.yml (Bonus - Automated dependency updates)
# ==============================================================================
---
version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "taublast"  # Replace with actual maintainer username
    assignees:
      - "taublast"  # Replace with actual maintainer username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
