name: Build and Test (Windows)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    # Install MAUI workloads on Windows
    - name: Install MAUI Workloads
      run: |
        dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
    
    - name: Restore dependencies
      run: dotnet restore src/Breakout.csproj
    
    - name: Build
      run: dotnet build src/Breakout.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test src/Breakout.csproj --no-build --configuration Release --verbosity normal
