# ==============================================================================
# FILE: .github/workflows/build-release.yml
# ==============================================================================
name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: 'src/Breakout.csproj'

jobs:
  build-android:
    name: Build Android
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install MAUI workloads
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui
        dotnet workload install android
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build Android APK (Debug)
      run: |
        dotnet build ${{ env.PROJECT_PATH }} `
          -c Debug `
          -f net9.0-android `
          --no-restore
          
    - name: Build Android APK (Release)
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} `
          -c Release `
          -f net9.0-android `
          --no-restore `
          -o ./artifacts/android
          
    - name: Upload Android artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./artifacts/android/**/*.apk
        retention-days: 30

  # iOS build temporarily disabled due to Xcode version requirement
  # .NET 9 requires Xcode 16.4, but GitHub runners currently have 15.4
  build-ios:
    name: Build iOS (Skipped - Xcode Version)
    runs-on: ubuntu-latest
    
    steps:
    - name: Skip iOS Build
      run: |
        echo "⚠️ iOS build skipped: .NET 9 requires Xcode 16.4, but GitHub macOS runners currently have 15.4"
        echo "This will be enabled once GitHub updates their macOS runners"
        echo "See: https://aka.ms/xcode-requirement"

  # MacCatalyst build temporarily disabled for same reason
  build-maccatalyst:
    name: Build MacCatalyst (Skipped - Xcode Version)  
    runs-on: ubuntu-latest
    
    steps:
    - name: Skip MacCatalyst Build
      run: |
        echo "⚠️ MacCatalyst build skipped: .NET 9 requires Xcode 16.4, but GitHub macOS runners currently have 15.4"
        echo "This will be enabled once GitHub updates their macOS runners"
        echo "See: https://aka.ms/xcode-requirement"

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install MAUI workloads
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build Windows (Debug)
      run: |
        dotnet build ${{ env.PROJECT_PATH }} `
          -c Debug `
          -f net9.0-windows10.0.19041.0 `
          --no-restore
          
    - name: Build Windows (Release)
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} `
          -c Release `
          -f net9.0-windows10.0.19041.0 `
          --no-restore `
          -r win-x64 `
          --self-contained false `
          -o ./artifacts/windows
          
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: ./artifacts/windows/**
        retention-days: 30

  create-release:
    name: Create Release
    needs: [build-android, build-ios, build-maccatalyst, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && always()
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./release-artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./release-artifacts/**/*
        draft: true
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## 🎮 Breakout Game Release
          
          ### Available Platforms
          - ✅ **Android**: APK included
          - ✅ **Windows**: App included  
          - ⚠️ **iOS/MacCatalyst**: Temporarily disabled due to Xcode version requirements
          
          ### Notes
          iOS and MacCatalyst builds are temporarily disabled because .NET 9 requires Xcode 16.4, 
          but GitHub macOS runners currently have Xcode 15.4. These will be re-enabled when GitHub 
          updates their runners.
